name: mitocracia
favicon: null
layout_spectrum: 0.42170161637477577
typography_spectrum: 0.13231770764105022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6465643637347966
  lightness: 0.5252542232628912
  saturation: 0.49481133348308504
  rhythmicContrast: 0.3299683325458318
purpose: []
